# podman compose up --build -d
services:
  app:
    build: .
    container_name: widget-server
    ports:
      - 3000:3333
    environment:
      - CLOUDFARE_ACCOUNT_ID=#
      - CLOUDFARE_ACCESS_KEY_ID=#
      - CLOUDFARE_SECRET_ACCESS_KEY=#
      - CLOUDFARE_BUCKET=#
      - CLOUDFARE_PUBLIC_URL=http://localhost
      - DATABASE_URL=postgresql://docker:docker@db:5432/widget_server
    networks:
      - widget
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=widget_server
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - widget
      - db

# I'm using the default drivers for each,
# we could hide them and it would be inferred automatically
volumes:
  db:
    driver: local
networks:
  widget:
    driver: bridge
  db:
    driver: bridge
